name: skillbox_2
channels:
  - conda-forge
dependencies:
  - python=3.12.4
  - requests
  - selenium
  - pip
  - pip:
      - webdriver-manager==4.0.2
  - pytest
  - allure-pytest
  - flake8
  - pytest-playwright